-- MySQL Script generated by MySQL Workbench
-- vie 09 abr 2021 16:27:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema politics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema politics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `politics` DEFAULT CHARACTER SET latin1 ;
USE `politics` ;

-- -----------------------------------------------------
-- Table `politics`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`partido` (
  `id` BIGINT(20) NOT NULL,
  `afiliados` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`candidate` (
  `id` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(150) NULL DEFAULT NULL,
  `votos` INT(11) NOT NULL,
  `partido_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK40xxg1yrjx9x9lro7wjg2o8sv` (`partido_id` ASC),
  CONSTRAINT `FK40xxg1yrjx9x9lro7wjg2o8sv`
    FOREIGN KEY (`partido_id`)
    REFERENCES `politics`.`partido` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`candidate_opiniones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`candidate_opiniones` (
  `candidate_id` BIGINT(20) NOT NULL,
  `opiniones` VARCHAR(255) NULL DEFAULT NULL,
  `opiniones_order` INT(11) NOT NULL,
  PRIMARY KEY (`candidate_id`, `opiniones_order`),
  CONSTRAINT `FKm78r379m5dlyo42rnyvu983wr`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `politics`.`candidate` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`promesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`promesa` (
  `id` BIGINT(20) NOT NULL,
  `accion_prometida` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`candidate_promesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`candidate_promesas` (
  `candidate_id` BIGINT(20) NOT NULL,
  `promesas_id` BIGINT(20) NOT NULL,
  `promesas_order` INT(11) NOT NULL,
  PRIMARY KEY (`candidate_id`, `promesas_order`),
  UNIQUE INDEX `UK_iemkdcv2ojfhi5ak05n4aa7yq` (`promesas_id` ASC),
  CONSTRAINT `FK8d6klivbamr1y9erqt7lqsidg`
    FOREIGN KEY (`promesas_id`)
    REFERENCES `politics`.`promesa` (`id`),
  CONSTRAINT `FKaluived3hv625vuts2nosy924`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `politics`.`candidate` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`flyway_schema_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`flyway_schema_history` (
  `installed_rank` INT(11) NOT NULL,
  `version` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(200) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `script` VARCHAR(1000) NOT NULL,
  `checksum` INT(11) NULL DEFAULT NULL,
  `installed_by` VARCHAR(100) NOT NULL,
  `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `execution_time` INT(11) NOT NULL,
  `success` TINYINT(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  INDEX `flyway_schema_history_s_idx` (`success` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`peronista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`peronista` (
  `populista` BIT(1) NULL DEFAULT NULL,
  `id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKlu708sow3a4gdg7osdplsfwg4`
    FOREIGN KEY (`id`)
    REFERENCES `politics`.`partido` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`preservativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`preservativo` (
  `fecha_creacion` DATE NULL DEFAULT NULL,
  `id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKtaeg14v863tcgbawsvdmnsh7u`
    FOREIGN KEY (`id`)
    REFERENCES `politics`.`partido` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`zona` (
  `id` BIGINT(20) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `politics`.`zona_candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `politics`.`zona_candidates` (
  `zona_id` BIGINT(20) NOT NULL,
  `candidates_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`zona_id`, `candidates_id`),
  UNIQUE INDEX `UK_qmxevuyc3afc3ey8mjio0duk0` (`candidates_id` ASC),
  CONSTRAINT `FKac0j420o9agfuvhdrnhpls9gv`
    FOREIGN KEY (`candidates_id`)
    REFERENCES `politics`.`candidate` (`id`),
  CONSTRAINT `FKtlqx31v2t3q557nmded1g8sa4`
    FOREIGN KEY (`zona_id`)
    REFERENCES `politics`.`zona` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
